import product1 from'./MenuItem/images/b1.png';

export const menuItemsData = [
    {
      id: 1,
      name: 'Mediterranean  Salad',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: product1,
    },
    {
      id: 2,
      name: 'Summer Asian Slaw',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: product1,
    },
    {
      id: 3,
      name: 'Burger',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: product1,
    },
    {
      id: 4,
      name: 'white sauce pasta',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: product1,
    },
    {
      id: 5,
      name: 'butterfly pasta',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: product1,
    },
    {
      id: 6,
      name: 'tooty fruity bowl',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: product1,
    },
    {
      id: 7,
      name: 'granola cereal bowl',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: product1,
    },
    {
      id: 8,
      name: 'palm bowl',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: product1,
    },
    {
      id: 9,
      name: 'tigela smoothie',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: product1,
    },
    {
      id: 10,
      name: 'breakfast cereal',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: product1,
    },
    {
      id: 11,
      name: 'cuisine of hawaii',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: product1,
    },
    {
      id: 12,
      name: 'fried chicken',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: product1,
    },
    {
      id: 13,
      name: 'greek salad',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: product1,
    },
    {
      id: 14,
      name: 'hamburger',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img:product1,
    },
    {
      id: 15,
      name: 'israeli salad',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: product1,
    },
    {
      id: 16,
      name: 'Pizza Pasta',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: product1,
    },
    {
      id: 17,
      name: 'Pizza',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img:product1,
    },
  ];
  